#!/bin/sh
set -euo pipefail
mkdir -p /newroot
mount -t tmpfs root /newroot
find / -mindepth 1 -maxdepth 1 ! -path /newroot -print0 | xargs -0 cp -at /newroot
# pivot_root does not work if the rootfs is a ramfs/tmpfs, so we switch root on another tmpfs as a workaround
exec switch_root /newroot /sbin/init "$@" || sh
