#!/bin/sh
set -eu
# Some programs (e.g. containerd) refuse to work if / is a "rootfs" mount, as in an initramfs.
# So, we need to copy all the files into a new tmpfs and "switch_root" to it
mkdir -p /newroot
mount -t tmpfs root /newroot
find / -mindepth 1 -maxdepth 1 ! -name newroot -exec cp -at /newroot {} +
exec switch_root /newroot /sbin/init "$@"
