---
build:
  stage: build
  image: crazymax/docker:latest
  services:
    - docker:dind
  variables:
    TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    DOCKER_BUILDKIT: "1"
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker buildx build -t $TAG --push .
