---
build:
  stage: build
  image: docker:27.0.3
  services:
    - name: moby/buildkit:v0.14.1
      alias: buildkitd
      command: ["--addr", "tcp://0.0.0.0:9000"]
  before_script:
    - docker buildx create --use --driver remote tcp://buildkitd:9000
    - echo $DOCKER_AUTH_CONFIG >~/.docker/config.json
  variables:
    PLATFORMS: linux/amd64,linux/arm64
    TAG: $CI_COMMIT_TAG
  script:
    - docker buildx bake all
    - if [[ "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]]; then docker buildx bake --push; fi
