---
build:
  stage: build
  image: docker:latest
  services:
    - name: moby/buildkit:latest
      alias: buildkitd
      command: ["--addr", "tcp://0.0.0.0:9000"]
  variables:
    REPOSITORY: ${CI_REGISTRY_IMAGE}
    TAG: ${CI_COMMIT_REF_NAME}
  before_script:
    - docker buildx create --use --driver remote tcp://buildkitd:9000
    - >
      printf >~/.docker/config.json '{"auths":{"%s":{"username":"%s","password":"%s"}}}\n'
      $CI_REGISTRY $CI_REGISTRY_USER $CI_REGISTRY_PASSWORD
  script:
    - docker buildx bake lint
    - docker buildx bake test
    - for EXT in efi img qcow2 iso; do test -f out/claylinux.${EXT}; done
    - docker buildx bake --push
