---
stages:
  - lint
  - build

lint:
  stage: lint
  image: koalaman/shellcheck-alpine:stable
  before_script:
    - shellcheck --version
  script:
    - grep -rlE '^#!/bin/(ba)?sh' . | xargs shellcheck

build:
  stage: build
  services:
    - docker:dind
  image: docker:latest
  variables:
    NAMESPACE: ${CI_REGISTRY_IMAGE}
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker compose build
    - docker compose push

