---
build:
  stage: build
  image:
    name: moby/buildkit:latest
    entrypoint: [""]
  variables:
    TAG: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
  before_script:
    - mkdir -p ~/.docker
    - AUTH=$(echo -n "${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD}" | base64)
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$AUTH\"}}}" > ~/.docker/config.json
  script:
    - buildctl-daemonless.sh build
      --frontend=dockerfile.v0
      --local context=.
      --local dockerfile=.
      --output name=${TAG},type=image,push=true
