---
include:
  - project: sprat/gitlab-ci
    file:
      - /templates/docker.yml

stages:
  - validate
  - build

validate:
  extends: .docker
  stage: validate
  script:
    - docker buildx bake lint

build:
  extends: .docker
  variables:
    PLATFORMS: linux/amd64,linux/arm64
    REPOSITORY: ${CI_REGISTRY_IMAGE}
    TAG: ${CI_COMMIT_REF_NAME}
  script:
    - docker buildx create --use --bootstrap --platform "$PLATFORMS"
    - docker buildx bake all --push
    - for EXT in efi img qcow2 iso; do test -f out/claylinux.${EXT}; done
