---
stages:
  - lint
  - build

lint:
  stage: lint
  image: koalaman/shellcheck-alpine:stable
  before_script:
    - shellcheck --version
  script:
    - grep -rlE '^#!/bin/(ba)?sh' . | xargs shellcheck

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    NAMESPACE: ${CI_REGISTRY_IMAGE}
  before_script:
    - docker version
    - docker buildx version
    - echo ${CI_REGISTRY_PASSWORD} | docker login -u ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
  script:
    - docker buildx bake --push

