---
include:
  - project: 'sprat/gitlab-ci'
    file:
      - '/templates/yamllint.yml'
      - '/templates/shellcheck.yml'
      - '/templates/hadolint.yml'
      - '/templates/docker.yml'

stages:
  - validate
  - build

yamllint:
  extends: .yamllint

shellcheck:
  extends: .shellcheck

hadolint:
  extends: .hadolint

build:
  extends: .docker
  variables:
    PLATFORMS: linux/amd64,linux/arm64
    REPOSITORY: ${CI_REGISTRY_IMAGE}
    TAG: ${CI_COMMIT_REF_NAME}
  script:
    - docker buildx create --use --bootstrap --platform "$PLATFORMS"
    - docker buildx bake --push
