---
build:
  stage: build
  image: docker:latest
  services:
    - name: moby/buildkit:latest
      alias: buildkitd
      command: ["--addr", "tcp://0.0.0.0:9000"]
  before_script:
    - docker buildx create --use --driver remote tcp://buildkitd:9000
    - echo $DOCKER_AUTH_CONFIG >~/.docker/config.json
  script:
    - docker buildx bake lint
    - docker buildx bake test
    - for EXT in efi img qcow2 iso; do test -f out/claylinux.${EXT}; done
    - TAG=${CI_COMMIT_TAG} docker buildx bake --push
