#!/bin/sh
set -eu

build() {
	docker buildx bake test "$@"
	# ./claytest build --set test.args.FORMAT=iso
}

run() {
	# machine:
	# - q35 correspond to a modern PC
	# - use some accelerators if available: kvm, windows hypervisor platform, or tcg as a fallback
	qemu-system-x86_64 \
	-machine q35,accel=kvm:whpx:tcg \
	-m 1G \
	-nodefaults \
	-nographic \
	-serial mon:stdio \
	-netdev "${1:-user}",id=net \
	-device virtio-net,netdev=net \
	-device virtio-rng \
	-hda out/claylinux.img
	#-cdrom out/claylinux.iso
}

usage() {
	cat <<-EOF
	Usage: $(basename "$0") COMMAND [...]

	Commands:
	  build [...]       build the test image (with docker buildx bake)
	  run [NETDEV]      run the test image (with qemu)
	EOF
}

case "${1:-}" in
	build|run)
		"$@"
		;;
	*)
		usage
		exit 1
		;;
esac
