#!/bin/bash
set -euo pipefail

build() {
	docker buildx bake "$@"
}

test() {
	format=raw
	if [[ -n "${1:-}" ]]; then
		format=$1
		shift
	fi

	# build the test OS image
	docker buildx bake test --set test.args.FORMAT="$format" "$@"

	qemu_bin=qemu-system-x86_64
	accelerator=kvm

	# special case for WSL on Microsoft Windows
	if [[ -n "${WSL_DISTRO_NAME:-}" ]]; then
		qemu_bin=${qemu_bin}.exe
		accelerator=whpx
	fi

	name=out/claylinux
	case "$format" in
		raw)
			boot_opts=(-drive "file=${name}.img,format=raw")
			;;
		iso)
			boot_opts=(-drive "file=${name}.iso,media=cdrom")
			;;
		files)
			# shellcheck source=/dev/null
			source "${name}"/boot.env
			boot_opts=(-kernel "${name}"/"$KERNEL" -initrd "${name}"/initramfs.img -append "$CMDLINE")
			;;
		*)
			echo "Error: invalid format '$format'"
			exit 1
			;;
	esac

	# machine:
	# - q35 correspond to a modern PC
	# - use some accelerators if available: kvm, windows hypervisor platform, or tcg as a fallback
	"$qemu_bin" \
	-machine q35,accel=${accelerator}:tcg \
	-m 2G \
	-nodefaults \
	-nographic \
	-serial mon:stdio \
	-netdev user,id=net \
	-device virtio-net,netdev=net \
	-device virtio-rng \
	"${boot_opts[@]}"
}

usage() {
	cat <<-EOF
	Usage: $(basename "$0") COMMAND [...]

	Commands:
	  build [...]    build the docker images
	  test [FORMAT]  build & run the test OS (with qemu)
	EOF
}

case "${1:-}" in
	build|test)
		"$@"
		;;
	*)
		usage
		exit 1
		;;
esac
