#!/bin/sh
set -eu

build() {
	docker buildx bake test "$@"
}

run() {
	qemu-system-x86_64 \
	-M q35 \
	-m 1G \
	-nodefaults \
	-nographic \
	-serial mon:stdio \
	-netdev "${1:-user}",id=net \
	-device virtio-net,netdev=net \
	-device virtio-rng \
	-boot d \
	-cdrom out/claylinux.iso
}

usage() {
	cat <<-EOF
	Usage: $0 COMMAND [...]

	Commands:
	  build [...]       build the test image (with docker buildx bake)
	  run [NETDEV]      run the test image (with qemu)
	EOF
}

case "${1:-usage}" in
	build|run)
		"$@"
		;;
	*)
		usage
		exit 1
		;;
esac
