---
# Use "docker compose run emulator" to execute the VM, not "docker compose up"
# Otherwise you won't be able to interact with it
services:
  emulator: &emulator
    image: claylinux/emulator
    pull_policy: build
    build:
      context: emulator
      args:
        FORMAT: ${FORMAT:-efi}
    network_mode: host
    stdin_open: true
    tty: true

  emulator-accel:
    <<: *emulator
    devices:
      - /dev/kvm
    command:
      - -accel
      - kvm
      - -cpu
      - host
