#!/bin/sh
set -eu

: "${NETDEV:=user}"

docker buildx bake test

qemu-system-x86_64 \
-M q35 \
-m 1G \
-nodefaults \
-nographic \
-serial mon:stdio \
-netdev "$NETDEV",id=net \
-device virtio-net,netdev=net \
-device virtio-rng \
-boot d \
-cdrom out/claylinux.iso
