name: CI

"on": push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/bake-action@v5
        with:
          targets: all
          push: ${{ github.ref == 'refs/heads/master' || github.ref_type == 'tag' }}
        env:
          PLATFORMS: linux/amd64,linux/arm64
          TAG: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
