name: CI

"on": push

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ case(github.ref == 'refs/heads/master' || github.ref_type == 'tag', 'release', null) }}
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-qemu-action@v4
      - uses: docker/setup-buildx-action@v4
      # Login only when the DOCKERHUB_USERNAME variable is provided via the job environment
      - if: vars.DOCKERHUB_USERNAME != null
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/bake-action@v7
        with:
          targets: all
          push: ${{ vars.DOCKERHUB_USERNAME != null }}
        env:
          PLATFORMS: linux/amd64,linux/arm64
          TAG: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
